---
- name: "Update Packages"
  apt:
    update_cache: yes
    upgrade: dist
  when:
    - "(ansible_os_family | lower) == 'debian'"
  tags:
    - "packages"
  notify: "reboot"

- name: "Clean Packages"
  apt:
    autoremove: yes
    purge: yes
  when:
    - "(ansible_os_family | lower) == 'debian'"
  tags:
    - "packages"
